// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nadrbejtyhibqqdnyhme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZHJiZWp0eWhpYnFxZG55aG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTI0MTEsImV4cCI6MjA2OTUyODQxMX0.m-uNESvODAbzEZ-bUujiCiYjwC2bvNI9fpShy8eBurU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});